### ISSUE TITLE
h2oを試す

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-infra#18]

**Comment by fukuiretu** [comment]
とりあえずMac上で動かしてみた

ref: http://blog.sarabande.jp/post/115987488918

**Comment by fukuiretu** [comment]
Next: リバプロでRailsまで

**Comment by fukuiretu** [comment]
ローカルでunicorn起動
`unicorn_rails -c config/unicorn.rb -E development -p 5000 -D`

**Comment by fukuiretu** [comment]
ref: h2oとUnixドメインソケット http://qiita.com/cubicdaiya/items/d6f3a165fa29e199afb1

**Comment by fukuiretu** [comment]
tcpのリバプロは以下の設定でいけた

/usr/local/etc/h2o/h2o.conf

```
listen:
  port: 8080
hosts:
  default:
    paths:
      /static:
        file.dir: /usr/local/var/h2o/
      /:
        proxy.reverse.url: http://127.0.0.1:5000/
    access-log: /dev/stdout
```

**Comment by fukuiretu** [comment]
以下の設定でunixドメインソケットでリバプロしたら`failed to connect to host`と言われた...

```
listen:
  port: 8080
hosts:
  default:
    paths:
      /static:
        file.dir: /usr/local/var/h2o/
      /:
        proxy.reverse.url: http://[unix:/tmp/ikyusan-api_unicorn.sock]/
    access-log: /dev/stdout
```

**Comment by fukuiretu** [comment]
unicronをtcpで起動してたからあかんかった。。いけたぞーーーー。あとh2oのソース見たら、`reproxy: ON`っての付けてたので、最終的に以下のようになった。

```
listen:
  port: 8080
hosts:
  default:
    paths:
      /static:
        file.dir: /usr/local/var/h2o/
      /:
        proxy.reverse.url: http://[unix:/tmp/ikyusan-api_unicorn.sock]/
    access-log: /dev/stdout
reproxy: ON
```
